# Generated by Django 4.2.4 on 2023-09-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('desc', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
