# Generated by Django 4.2.4 on 2023-09-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
